# docker-compose.yml
version: '2'
services:
  prometheus:
    image: prom/prometheus:0.18.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  node-exporter:
    image: prom/node-exporter:0.12.0rc1
    ports:
      - '9100:9100'

  grafana:
    image: grafana/grafana:3.0.0-beta7
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

volumes:
    prometheus_data: {}
    grafana_data: {}
